In [1]:
import pandas as pd
import glob
import numpy as np

In [ ]:
### random problems

In [8]:
#scheds = glob.glob("/Users/benplatten/workspace/UvA_Thesis/UvA_MSc_Thesis/dev/scheduling_problems/schedules/*.csv")
scheds = glob.glob("scheduling_problems/schedules/*.csv")

In [9]:
scheds[0]

'scheduling_problems/schedules/schedule_0012.csv'

In [12]:
scheds[0].split('/')[1]

'schedules'

In [10]:
scheds[0].split('/')[9].split('_')[1].split('.')[0]

IndexError: list index out of range

In [11]:
scheds[0].split('/')[1].split('_')[1].split('.')[0]

IndexError: list index out of range

In [95]:
pools = glob.glob("/Users/benplatten/workspace/UvA_Thesis/UvA_MSc_Thesis/dev/scheduling_problems/pools/*.csv")

pools[0]

'/Users/benplatten/workspace/UvA_Thesis/UvA_MSc_Thesis/dev/scheduling_problems/pools/pool_0005.csv'

In [86]:
def updateDataIndex():
    scheds = glob.glob("scheduling_problems/schedules/*.csv")
    pools = glob.glob("scheduling_problems/pools/*.csv")
    s_len = []
    Schedule = []
    for sched in sorted(scheds):
        s_len.append(len(pd.read_csv(sched)))
        Schedule.append(sched.split('/')[2].split('_')[1].split('.')[0])
    p_len = []
    Pool = []
    for pool in sorted(pools):
        p_len.append(len(pd.read_csv(pool)))
        Pool.append(pool.split('/')[2].split('_')[1].split('.')[0])

    Pool += ['nan'] * (len(Schedule) - len(Pool))
    p_len += ['nan'] * (len(s_len) - len(p_len))

    data = {'Schedule':Schedule,'shifts':s_len,'Pool':Pool,'employees':p_len}

    di = pd.DataFrame(data)
    
    return di

In [90]:
updateDataIndex()

Schedule  shifts  Pool employees
0      0001       4  0001         2
1      0002       6  0002         3
2      0003       8  0003         4
3      0004       5  0004         5
4      0005       3  0005         6
5      0006       4  0006         7
6      0007       5  0007         8
7      0008       3  0008         4
8      0009       6  0009         4
9      0010       7  0010         4
10     0011       7  0011         4
11     0012       8  0012         4
12     0013       8  0013         4
13     0014       8  0014         4
14     0015       8  0015         4
15     0016       8  0016         4
16     0017       8  0017         4
17     0018       8  0018         4
18     0019       8  0019         4
19     0020       8  0020         4
20     0021       8  0021         4
21     0022       8  0022         4
22     0023       8  0023         4
23     0024       8  0024         4
24     0025       8  0025         4
25     0026       8  0026         4
26     0027       8  0027         4
27     0028       8  0028         4
28     0029       8  0029         4
29     0030       8  0030         4
30     0031       8  0031         4
31     0032       8  0032         4
32     0033       8  0033         4
33     0034       8  0034         4
34     0035       8  0035         4
35     0036       8  0036         4
36     0037       8  0037         4
37     0038       8  0038         4
38     0039       8  0039         4
39     0040       8  0040         4
40     0041       8  0041         4
41     0042       8  0042         4
42     0043       8  0043         4
43     0044       8  0044         4
44     0045       8  0045         4
45     0046       8  0046         4
46     0047       8  0047         4
47     0048       8   nan       nan
48     0049       8   nan       nan
49     0050       8   nan       nan
50     0051       8   nan       nan
51     0052       8   nan       nan

In [52]:
di = updateDataIndex()
di.to_csv('data_index.csv',index=False)

In [83]:
def problemIndex():
    di = updateDataIndex()
    #pd.read_csv('data_index.csv',dtype=str)
    di['shifts'] = di['shifts'].astype(int) 
    
    pi = pd.DataFrame(columns=['Schedule', 'Pool'])

    scheds = di.Schedule.to_list()
    pools = di.Pool.to_list()
    pools = [x for x in pools if str(x) != 'nan']

    for sched in scheds:
        for pool in pools:
            pi.loc[0 if pd.isnull(pi.index.max()) else pi.index.max() + 1] = [sched] + [pool]

    pi = pd.merge(pi, di[['Schedule', 'shifts']], on ='Schedule', how ='left')
    pi = pd.merge(pi, di[['Pool', 'employees']], on ='Pool', how ='left')
    pi['employees'] = pi['employees'].astype(int)
    pi['Nodes'] = pi['shifts'] + pi['employees']
    pi['Ratio'] = pi['shifts'] / pi['employees']
    
    return pi


In [89]:
problemIndex()
#pi.to_csv('problem_index.csv', index=False)

Schedule  Pool  shifts  employees  Nodes     Ratio
0        0001  0001       4          2      6  2.000000
1        0001  0002       4          3      7  1.333333
2        0001  0003       4          4      8  1.000000
3        0001  0004       4          5      9  0.800000
4        0001  0005       4          6     10  0.666667
...       ...   ...     ...        ...    ...       ...
2439     0052  0043       8          4     12  2.000000
2440     0052  0044       8          4     12  2.000000
2441     0052  0045       8          4     12  2.000000
2442     0052  0046       8          4     12  2.000000
2443     0052  0047       8          4     12  2.000000

[2444 rows x 6 columns]

In [2]:
# ON HOLD

# check if values are as expected   
    # sequential shift IDs
    # proper case spelling
# check that size is as expected

In [ ]:
scheds = glob.glob("schedules/*.csv")
pools = glob.glob("pools/*.csv")

In [ ]:
shift_day_of_week = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
shift_type = ['Morning','Evening']


In [ ]:
errorDict = {}
for sched in scheds:
        id = sched.split('/')[1].split('_')[1].split('.')[0]
        s = pd.read_csv(sched,dtype={'shift_id':'str'})
        
        #stateDict[id] = 
        

In [ ]:
for pool in pools:
    id = pool.split('/')[1].split('_')[1].split('.')[0]
    p = pd.read_csv(pool,dtype={'employee_id':'str'})
    #stateDict[id] = 

In [ ]:
# convert all to matrices
# check for unqiueness

In [6]:
def matrify(pool, schedule):
    schedule = pd.get_dummies(schedule,drop_first=True)
    #shift_features = schedule.shape[1]
    for i in pd.get_dummies(pool).columns.to_list():
        schedule[i] = 0

    return schedule.to_numpy()

In [8]:
def problemValidation():
    scheds = glob.glob("schedules/*.csv")
    pools = glob.glob("pools/*.csv")

    stateDict = {}
    for sched in scheds:
        for pool in pools:
            id = sched.split('/')[1].split('_')[1].split('.')[0]+pool.split('/')[1].split('_')[1].split('.')[0]
            s = pd.read_csv(sched,dtype={'shift_id':'str'})
            p = pd.read_csv(pool,dtype={'employee_id':'str'})
            stateDict[id] = matrify(p, s)

    dupes=[]
    for key, value in stateDict.items(): 
        for k, v in stateDict.items(): 
            if key != k:
                if np.array_equal(value, v):
                    dupes.append((key,k))

    print(f"{len(dupes)} duplicate problems found in data set.")

    return dupes

In [11]:
dupes =  problemValidation()

0 duplicate problems found in data set.


In [ ]:
### problem loader 

In [36]:
def problemLoader(max_shifts):
    pi = problemIndex()
    pi.head()

    selectedProbs = pi[pi['shifts'] <=max_shifts] 
    selectedProbs



    glob_list = []
    for i in range(len(selectedProbs)):
        s = selectedProbs['Schedule'].iloc[i]
        p = selectedProbs['Pool'].iloc[i]
        glob_list.append((s,p))

    return glob_list

#problemLoader(max_shifts=5)

In [ ]:
### OneHotEncoder ###

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import joblib

In [25]:
p = "pool_0001"
s = "schedule_TEST"

pool, schedule = pd.read_csv(f'scheduling_problems/pools/{p}.csv',dtype={'employee_id':'str'}), \
                 pd.read_csv(f'scheduling_problems/{s}.csv',dtype={'shift_id':'str'})


In [35]:
ohe = OneHotEncoder(categories=['Monday','Tuesday','Wednesday','Thursday','Friday'],
                    drop='first',sparse=False,handle_unknown='error')
#ohe.fit(schedule[['shift_day_of_week','shift_type']])

ohe.categories


['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [37]:
ohe = OneHotEncoder(categories=[1,2,3,4,5],
                    drop='first',sparse=False,handle_unknown='error')
#ohe.fit(schedule[['shift_day_of_week','shift_type']])

ohe.categories

[1, 2, 3, 4, 5]

In [40]:
schedule['shift_type'] 

0    Morning
1    Evening
2    Morning
3    Evening
4    Morning
Name: shift_type, dtype: object

In [42]:
schedule['shift_day_of_week'] = schedule['shift_day_of_week'].replace(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],[1, 2, 3, 4, 5])
schedule['shift_day_of_week'].value_counts()

schedule['shift_type'] = schedule['shift_type'].replace(['Morning', 'Evening'],[1, 2])
schedule['shift_type'].value_counts()

1    3
2    2
Name: shift_type, dtype: int64

In [45]:

ohe = OneHotEncoder(drop='first',sparse=False,handle_unknown='error')
ohe.fit(schedule[['shift_day_of_week','shift_type']])

joblib.dump(ohe,"shiftFeatureEncoding.joblib")

sfEncodings = joblib.load('shiftFeatureEncoding.joblib')

sfEncodings = ohe

In [46]:
sfEncodings.get_feature_names_out()

array(['shift_day_of_week_2', 'shift_day_of_week_3',
       'shift_day_of_week_4', 'shift_day_of_week_5', 'shift_type_2'],
      dtype=object)

In [11]:
p = "pool_0001"
s = "schedule_TEST"

pool, schedule = pd.read_csv(f'scheduling_problems/pools/{p}.csv',dtype={'employee_id':'str'}), \
                 pd.read_csv(f'scheduling_problems/{s}.csv',dtype={'shift_id':'str'})

sfEncodings = joblib.load('shiftFeatureEncoding.joblib')

shifts = pd.get_dummies(schedule[['shift_id']],drop_first=True)
sfEncoded =  sfEncodings.transform(schedule[['shift_day_of_week','shift_type']])
shift_features = pd.DataFrame(sfEncoded, columns=sfEncodings.get_feature_names_out())

schedule = pd.merge(shifts, shift_features, left_index=True, right_index=True)

#self.shift_features = schedule.shape[1]

# OR 
# self.shift_features = shift_features.shape[1]

for i in pd.get_dummies(pool).columns.to_list():
    schedule[i] = 0

schedule

shift_id_1  shift_id_2  shift_id_3  shift_day_of_week_Monday  \
0           0           0           0                       1.0   
1           1           0           0                       0.0   
2           0           1           0                       0.0   
3           0           0           1                       0.0   
4           0           0           1                       0.0   

   shift_day_of_week_Thursday  shift_day_of_week_Tuesday  \
0                         0.0                        0.0   
1                         0.0                        1.0   
2                         0.0                        0.0   
3                         1.0                        0.0   
4                         0.0                        0.0   

   shift_day_of_week_Wednesday  shift_type_Morning  employee_id_248509  \
0                          0.0                 1.0                   0   
1                          0.0                 0.0                   0   
2                          1.0                 1.0                   0   
3                          0.0                 0.0                   0   
4                          0.0                 1.0                   0   

   employee_id_508579  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0

In [ ]:
#### fix embeddings ####

In [80]:
p = "pool_0001"
s = "schedule_0010"

pool, schedule = pd.read_csv(f'scheduling_problems/pools/{p}.csv',dtype={'employee_id':'str'}), \
                 pd.read_csv(f'scheduling_problems/schedules/{s}.csv',dtype={'shift_id':'str'})

sfEncodings = joblib.load('shiftFeatureEncoding.joblib')

shifts = pd.get_dummies(schedule[['shift_id']],drop_first=True)
sfEncoded =  sfEncodings.transform(schedule[['shift_day_of_week','shift_type']])
shift_features = pd.DataFrame(sfEncoded, columns=sfEncodings.get_feature_names_out())

schedule = pd.merge(shifts, shift_features, left_index=True, right_index=True)

#self.shift_features = schedule.shape[1]

# OR 
# self.shift_features = shift_features.shape[1]

for i in pd.get_dummies(pool).columns.to_list():
    schedule[i] = 0

schedule


shift_id_1  shift_id_2  shift_id_3  shift_id_4  shift_id_5  shift_id_6  \
0           0           0           0           0           0           0   
1           1           0           0           0           0           0   
2           0           1           0           0           0           0   
3           0           0           1           0           0           0   
4           0           0           0           1           0           0   
5           0           0           0           0           1           0   
6           0           0           0           0           0           1   

   shift_day_of_week_Monday  shift_day_of_week_Thursday  \
0                       1.0                         0.0   
1                       0.0                         0.0   
2                       0.0                         0.0   
3                       0.0                         0.0   
4                       0.0                         0.0   
5                       0.0                         1.0   
6                       0.0                         0.0   

   shift_day_of_week_Tuesday  shift_day_of_week_Wednesday  shift_type_Morning  \
0                        0.0                          0.0                 1.0   
1                        1.0                          0.0                 1.0   
2                        1.0                          0.0                 0.0   
3                        0.0                          1.0                 1.0   
4                        0.0                          1.0                 0.0   
5                        0.0                          0.0                 1.0   
6                        0.0                          0.0                 1.0   

   employee_id_248509  employee_id_508579  
0                   0                   0  
1                   0                   0  
2                   0                   0  
3                   0                   0  
4                   0                   0  
5                   0                   0  
6                   0                   0

In [81]:
state = schedule.to_numpy()
state

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]])

In [82]:
print(len(pool))
print(len(schedule))

2
7


In [95]:
schedule.shape[1] - len(pool)

11

In [96]:
sf_start = len(schedule)-1
sf_end = schedule.shape[1] - len(pool)
sf_index = (sf_start,sf_end)
print(sf_index)

(6, 11)


In [97]:
state[:,sf_start:sf_end]

array([[1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [93]:
state

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]])

In [1]:
##### edge features 

In [8]:
numShifts = 4
numEmps = 2
num_ES_Edges = numShifts * numEmps
edge_ids = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
ES_ids = edge_ids[-num_ES_Edges:]
ES_ids

[8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
ES_edges=[]
for i in ES_ids:
    ES_edges.append((source[i],dest[i]))

ES_edges

[(4, 0), (4, 1), (4, 2), (4, 3), (5, 0), (5, 1), (5, 2), (5, 3)]

In [ ]:
shift = 3
emp = 1





In [66]:
##### get assignment data from state
import numpy as np
import torch

shift_feature_count = 8
num_shifts = 4

s = np.array([[0, 0, 0, 1, 0, 0, 0, 1, 0, 1],
              [1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
              [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
              [0, 0, 1, 0, 0, 1, 0, 0, 0, 0]])
state = torch.from_numpy(s)
shift_index = (torch.sum(state[:,shift_feature_count:],1) == 0).nonzero(as_tuple=True)[0][0]
shift_index

tensor(2)

In [67]:
if shift_index > 0:
    for i in range(shift_index):
        print(f"i: {i}")
        # get assignment data
        shift = i
        print(f"shift: {shift}")
        shift_data = state[shift,shift_feature_count:]
        #print(shift_data)
        assigned_emp = (state[shift,shift_feature_count:] == 1).nonzero(as_tuple=True)[0]
        print(f"assigned_emp: {assigned_emp}")
        

        # save data to edge
        edges = torch.FloatTensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]) # bg.edges()[0]
        # dest =                 ([4, 5, 4, 5, 4, 5, 4, 5, 0, 1, 2, 3, 0, 1, 2, 3])
        #edge_ids = torch.FloatTensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]) #bg.edges()[2]

        # edge index for shift-emp edge
        se_idx = (edges == shift).nonzero(as_tuple=True)[0][assigned_emp]
        print(f"se_idx {se_idx}")

        # edge index for emp-shift edge
        emp_id = torch.unique(edges)[num_shifts:][assigned_emp]
        #print(emp_id)
        #print(shift)
        es_idx = (edges == emp_id).nonzero(as_tuple=True)[0][shift]
        print(f"es_idx {es_idx}")

        #bg.edges[se_idx, es_idx].data['y'] = torch.ones(2)

i: 0
shift: 0
assigned_emp: tensor([1])
se_idx tensor([1])
es_idx 12
i: 1
shift: 1
assigned_emp: tensor([1])
se_idx tensor([3])
es_idx 13


In [29]:
state

tensor([[0, 0, 0, 1, 0, 0, 0, 1, 0, 1],
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 1, 0, 0, 0, 0]])

In [34]:
shift = shift_index-1
shift_data = state[shift_index-1,shift_feature_count:]
assigned_emp = (state[shift_index-1,shift_feature_count:] == 1).nonzero(as_tuple=True)[0]

In [35]:
print(shift)
print(assigned_emp)

tensor(0)
tensor([1])


In [42]:
# id index for shift-emp edge
edges = torch.FloatTensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5])
(edges == 3).nonzero(as_tuple=True)[0][0]

tensor(6)

In [49]:
# id index for emp-shift edge
emp_id = torch.unique(edges)[num_shifts:][assigned_emp]
print(emp_id)
print(shift)
(edges == emp_id).nonzero(as_tuple=True)[0][shift]

tensor([5.])
tensor(0)


tensor(12)

In [33]:
tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5])
tensor([4, 5, 4, 5, 4, 5, 4, 5, 0, 1, 2, 3, 0, 1, 2, 3])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#### problem batch

In [97]:
import random
problem_batch = [('0001','0001'),('0002','0001')]
prob = random.choice(problem_batch)
print(prob)
s = prob[0]
p = prob[1]

print(s)

('0002', '0001')
0002


In [100]:
problog= [('0002', '0001'),('0002', '0001'),('0002', '0001')]
with open('problog.txt', 'w') as f:
    for item in problog:
        f.write("%s\n" % str(item))

In [101]:
scores=[0.75, 1.0, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

data = pd.DataFrame.from_dict({'scores':scores})
data.to_csv(f"{filename}.csv",index=False)

scores
0    0.75
1    1.00
2    0.75
3    1.00
4    1.00
5    1.00
6    1.00
7    1.00
8    1.00