In [2]:
import pandas as pd

In [3]:
p = "pool_0001"
s = "schedule_0002"
pool, schedule = pd.read_csv(f'../dev/pools/{p}.csv',dtype={'employee_id':'str'}), \
                 pd.read_csv(f'../dev/schedules/{s}.csv',dtype={'shift_id':'str'})


In [4]:
pd.get_dummies(schedule,drop_first=True) #.columns

shift_id_1  shift_id_2  shift_id_3  shift_id_4  shift_id_5  \
0           0           0           0           0           0   
1           1           0           0           0           0   
2           0           1           0           0           0   
3           0           0           1           0           0   
4           0           0           0           1           0   
5           0           0           0           0           1   

   shift_day_of_week_Tuesday  shift_day_of_week_Wednesday  shift_type_morning  
0                          0                            0                   1  
1                          0                            0                   0  
2                          1                            0                   1  
3                          1                            0                   0  
4                          0                            1                   1  
5                          0                            1                   0

In [5]:
schedule = pd.get_dummies(schedule,drop_first=True)
shift_features = schedule.shape[1]
shift_features

8

In [6]:
for i in pd.get_dummies(pool).columns.to_list():
    schedule[i] = 0
schedule

shift_id_1  shift_id_2  shift_id_3  shift_id_4  shift_id_5  \
0           0           0           0           0           0   
1           1           0           0           0           0   
2           0           1           0           0           0   
3           0           0           1           0           0   
4           0           0           0           1           0   
5           0           0           0           0           1   

   shift_day_of_week_Tuesday  shift_day_of_week_Wednesday  shift_type_morning  \
0                          0                            0                   1   
1                          0                            0                   0   
2                          1                            0                   1   
3                          1                            0                   0   
4                          0                            1                   1   
5                          0                            1                   0   

   employee_id_248509  employee_id_508579  
0                   0                   0  
1                   0                   0  
2                   0                   0  
3                   0                   0  
4                   0                   0  
5                   0                   0

In [7]:
state = schedule.to_numpy()
state

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0]])

In [8]:
state[1,(shift_features+1)] = 1
state

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0]])

In [13]:
state[:,:shift_features]#[4:]

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 0]])

In [14]:
state[:,:shift_features][4:]

array([[0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 0]])

In [10]:
def check_b2b(nums):
    countb2b=0
    count=0
    for i in range(len(nums)):
        if nums[i]==1:
            count=count+1
            if count > 1:
                countb2b += 1                       
        else:
            count=0

    return countb2b

In [11]:
count_b2b = 0

for i in range(2):
    count_b2b += check_b2b(state[:,shift_features+i])

count_b2b

0