In [ ]:
# schedule 0001, pool 0001 -> state

['shift_id_1', 'shift_id_2', 'shift_id_3', 'shift_day_of_week_Tuesday', 'shift_type_morning']

[[0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 1 1 0 0]
 [0 0 1 1 0 0 0]]

In [ ]:
# schedule 0002, pool 0001 -> state

['shift_id_1', 'shift_id_2', 'shift_id_3', 'shift_id_4', 'shift_id_5','shift_day_of_week_Tuesday', 'shift_day_of_week_Wednesday','shift_type_morning']

[[0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 0 0 0]]

In [ ]:
torch.Size([2, 32])
torch.Size([32])
tensor([-0.1833, -0.1019], grad_fn=<ReshapeAliasBackward0>)


torch.Size([4, 32])
torch.Size([32])
tensor([0.0658, 0.0492, 0.0634, 0.0147], grad_fn=<ReshapeAliasBackward0>)